### ISSUE TITLE
favicon.ico is resent on every search

### ISSUE THREAD

**Issue by gurgalex** [rovermicrover/siralim-ultimate-ui#10]
For example, in the /creatures page it is sent when clicking the next page button.
![image](https://user-images.githubusercontent.com/28968644/136653106-12c36063-6d18-4a15-b3ae-c21e23a271ac.png)

**Comment by rovermicrover** [comment]
This is a known issue with Brave closing out
https://github.com/brave/browser-laptop/issues/2697
